spring:
  application:
    name: eurekaservice
  security:
    user:
      name: admin
      password: s3cr3t

server:
  port: 8761

eureka:
  client:
    # instance:
    #   preferIpAddress: true
    #   ipAddress: 172.16.12.155
    registerWithEureka: false
    fetchRegistry: false
    server:
      enableSelfPreservation: false
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://admin:s3cr3t@eurekaservice:8761/  