spring:
  application:
    name: eureka-service
  security:
    user:
      name: admin
      password: s3cr3t

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://admin:s3cr3t@eurekaservice:8761/eureka/
  server:
    enableSelfPreservation: false