spring:
  application:
    name: eurekaservice
  security:
    user:
      name: admin
      password: s3cr3t

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    # service-url:
    #   defaultZone: http://admin:s3cr3t@localhost:8761/eureka/
    server:
      enableSelfPreservation: false
      waitTimeInMsWhenSyncEmpty: 0